application:
  name: @project.name@
  description: @project.description@
  swagger:
    name: Rozuur
    url: https://github:com/rozuur/spring-boot-opinionated
    email:
    license:
      name: MIT License
      url: https://mit-license.org/

spring:
  liquibase:
    changeLog: classpath:/db/changelog/liquibase-master.yaml